# Generated by Django 4.1.7 on 2023-03-21 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('login_user', models.IntegerField(null=True)),
                ('sex', models.CharField(choices=[('男性', '男性'), ('女性', '女性')], max_length=2, verbose_name='性別')),
                ('age', models.IntegerField(null=True)),
                ('player_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('total_score', models.PositiveSmallIntegerField(verbose_name='スコア')),
                ('ob', models.PositiveSmallIntegerField(verbose_name='OB')),
                ('penalty', models.PositiveSmallIntegerField(verbose_name='ペナルティ率')),
                ('fw', models.PositiveSmallIntegerField(verbose_name='FWキープ率')),
                ('par_on', models.PositiveSmallIntegerField(verbose_name='パーオン率')),
                ('putt', models.PositiveSmallIntegerField(verbose_name='パット数')),
                ('stat_number', models.IntegerField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.person', verbose_name='プレイヤー')),
            ],
        ),
    ]
