# Generated by Django 4.1.7 on 2023-03-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='bunker',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='バンカー数'),
            preserve_default=False,
        ),
    ]
