# Generated by Django 4.1.7 on 2023-04-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_stat_bunker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='player_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
