# Generated by Django 4.1.1 on 2023-05-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_alter_person_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='stat_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
