# Generated by Django 3.2.16 on 2022-11-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0006_alter_stat_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='date',
            field=models.DateField(verbose_name='日付'),
        ),
    ]
