# Generated by Django 3.2.16 on 2023-01-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0008_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
