# Generated by Django 3.2.16 on 2023-01-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0009_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='contributor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
