# Generated by Django 3.2.16 on 2023-01-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0010_person_contributor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='contributor',
            new_name='login_user',
        ),
    ]
