# Generated by Django 3.2.16 on 2023-01-28 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0011_rename_contributor_person_login_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.person', verbose_name='プレイヤー'),
        ),
    ]
