# Generated by Django 3.2.16 on 2023-02-20 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0013_auto_20230220_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='login_user_id',
            new_name='login_user',
        ),
    ]
