# Generated by Django 3.2.16 on 2023-02-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0015_auto_20230220_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('男性', '男性'), ('女性', '女性')], max_length=2, verbose_name='性別'),
        ),
    ]
