# Generated by Django 3.2.16 on 2023-02-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0016_alter_person_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='ob',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='OB率'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='par_on',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='パーオン率'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='penalty',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ペナルティ率'),
        ),
    ]
