# Generated by Django 3.2.16 on 2023-03-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0019_alter_person_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='ob',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='OB'),
        ),
    ]
