# Generated by Django 3.2.16 on 2023-03-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0021_alter_person_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='fw',
            field=models.PositiveSmallIntegerField(verbose_name='FWキープ率'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='ob',
            field=models.PositiveSmallIntegerField(verbose_name='OB'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='par_on',
            field=models.PositiveSmallIntegerField(verbose_name='パーオン率'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='penalty',
            field=models.PositiveSmallIntegerField(verbose_name='ペナルティ率'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='putt',
            field=models.PositiveSmallIntegerField(verbose_name='パット数'),
        ),
    ]
