# Generated by Django 3.2.16 on 2023-03-10 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0023_stat_stat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='stat_id',
            new_name='stat_number',
        ),
    ]
