# Generated by Django 3.2.16 on 2023-03-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0024_rename_stat_id_stat_stat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='stat_number',
            field=models.IntegerField(),
        ),
    ]
