# Generated by Django 3.2.16 on 2023-03-10 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0025_alter_stat_stat_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='stat_number',
        ),
    ]
