# Generated by Django 3.2.16 on 2023-03-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0027_stat_stat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='player_number',
            field=models.IntegerField(null=True),
        ),
    ]
