# Generated by Django 3.2.18 on 2023-04-21 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
